import { ImpositionSettings } from '../types';

export interface JobTemplate {
  id: string;
  title: string;
  category: 'Folleto' | 'Tarjetas' | 'Flyer' | 'Libro' | 'Papelería';
  description: string;
  icon: string;
  badge: string;
  settings: Partial<ImpositionSettings>;
}

export const WORKSHOP_PRESETS: JobTemplate[] = [
  {
    id: 'booklet_a5_in_a4',
    title: 'Folleto / Cuadernillo A5 en Pliego A4',
    category: 'Folleto',
    description: 'El formato estándar: 2 páginas A5 por cara en pliego A4 apaisado. Se dobla al medio y queda tamaño A5 grapado.',
    icon: '📖',
    badge: 'A5 en A4',
    settings: {
      sheetPreset: 'A4',
      sheetWidth: 210,
      sheetHeight: 297,
      sheetOrientation: 'landscape',
      layoutMode: 'booklet',
      gridCols: 2,
      gridRows: 1,
      targetPagePreset: 'A5',
      targetPageWidth: 148.5,
      targetPageHeight: 210,
      duplexMode: 'long_edge',
      bindingEdge: 'left',
      marginTop: 8,
      marginBottom: 8,
      marginLeft: 8,
      marginRight: 8,
      gutterHorizontal: 0,
      gutterVertical: 0,
      drawCropMarks: true,
      cropMarkLength: 5,
      bleed: 3,
      scaleMode: 'fit',
    },
  },
  {
    id: 'manga_tankobon_b6_or_a5',
    title: 'Manga / Cómic Oriental (Lomo Derecho y Dobles Páginas)',
    category: 'Folleto',
    description: 'Encuadernación con lomo a la derecha (RTL) para Manga con división automática de páginas dobles panorámicas en caras internas.',
    icon: '🎌',
    badge: 'Manga RTL',
    settings: {
      sheetPreset: 'A4',
      sheetWidth: 210,
      sheetHeight: 297,
      sheetOrientation: 'landscape',
      layoutMode: 'booklet',
      gridCols: 2,
      gridRows: 1,
      targetPagePreset: 'A5',
      targetPageWidth: 148.5,
      targetPageHeight: 210,
      duplexMode: 'long_edge',
      bindingEdge: 'right',
      splitDoubleSpreads: true,
      marginTop: 6,
      marginBottom: 6,
      marginLeft: 6,
      marginRight: 6,
      gutterHorizontal: 0,
      gutterVertical: 0,
      drawCropMarks: true,
      cropMarkLength: 5,
      bleed: 2,
      scaleMode: 'fit',
    },
  },
  {
    id: 'booklet_a4_in_a3',
    title: 'Revista / Catálogo A4 en Pliego A3',
    category: 'Folleto',
    description: 'Revista tamaño carta/A4: 2 páginas A4 por cara en pliego A3 apaisado. Al doblar al medio queda A4 cerrado.',
    icon: '📑',
    badge: 'A4 en A3',
    settings: {
      sheetPreset: 'A3',
      sheetWidth: 297,
      sheetHeight: 420,
      sheetOrientation: 'landscape',
      layoutMode: 'booklet',
      gridCols: 2,
      gridRows: 1,
      targetPagePreset: 'A4',
      targetPageWidth: 210,
      targetPageHeight: 297,
      duplexMode: 'long_edge',
      bindingEdge: 'left',
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 10,
      marginRight: 10,
      gutterHorizontal: 0,
      gutterVertical: 0,
      drawCropMarks: true,
      cropMarkLength: 5,
      bleed: 3,
      scaleMode: 'fit',
    },
  },
  {
    id: 'booklet_a5_in_a3_4up',
    title: 'Folleto A5 en Pliego A3 (4 págs/cara)',
    category: 'Folleto',
    description: 'Aprovechamiento de pliego A3: entran 4 páginas A5 por cara (2 cols × 2 filas = 8 págs por hoja A3).',
    icon: '📚',
    badge: '4× A5 en A3',
    settings: {
      sheetPreset: 'A3',
      sheetWidth: 297,
      sheetHeight: 420,
      sheetOrientation: 'landscape',
      layoutMode: 'booklet',
      gridCols: 2,
      gridRows: 2,
      booklet4UpMode: 'cut_and_nest',
      targetPagePreset: 'A5',
      targetPageWidth: 148.5,
      targetPageHeight: 210,
      duplexMode: 'long_edge',
      bindingEdge: 'left',
      marginTop: 8,
      marginBottom: 8,
      marginLeft: 8,
      marginRight: 8,
      gutterHorizontal: 0,
      gutterVertical: 0,
      drawCropMarks: true,
      cropMarkLength: 5,
      bleed: 3,
      scaleMode: 'fit',
    },
  },
  {
    id: 'business_cards_10up_a4',
    title: '10 Tarjetas de Presentación (90×50 mm)',
    category: 'Tarjetas',
    description: '10 tarjetas en hoja A4 vertical con marcas de corte perimetrales listas para guillotinar.',
    icon: '📇',
    badge: '10x A4',
    settings: {
      sheetPreset: 'A4',
      sheetWidth: 210,
      sheetHeight: 297,
      sheetOrientation: 'portrait',
      layoutMode: 'step_and_repeat',
      gridCols: 2,
      gridRows: 5,
      targetPagePreset: 'BusinessCard_90x50',
      targetPageWidth: 90,
      targetPageHeight: 50,
      duplexMode: 'long_edge',
      marginTop: 15,
      marginBottom: 15,
      marginLeft: 15,
      marginRight: 15,
      gutterHorizontal: 0,
      gutterVertical: 0,
      drawCropMarks: true,
      cropMarkLength: 5,
      bleed: 2,
      scaleMode: 'fit',
    },
  },
  {
    id: 'flyers_4up_a4',
    title: '4 Volantes / Flyers A6 en Pliego A4',
    category: 'Flyer',
    description: 'Cuadrícula 2×2 en A4 apaisado con calles intermedias de 4 mm para corte limpio.',
    icon: '📄',
    badge: '4x A4',
    settings: {
      sheetPreset: 'A4',
      sheetWidth: 210,
      sheetHeight: 297,
      sheetOrientation: 'landscape',
      layoutMode: 'step_and_repeat',
      gridCols: 2,
      gridRows: 2,
      targetPagePreset: 'A6',
      targetPageWidth: 105,
      targetPageHeight: 148.5,
      duplexMode: 'long_edge',
      marginTop: 6,
      marginBottom: 6,
      marginLeft: 6,
      marginRight: 6,
      gutterHorizontal: 4,
      gutterVertical: 4,
      drawCropMarks: true,
      cropMarkLength: 5,
      bleed: 2,
      scaleMode: 'fit',
    },
  },
  {
    id: 'book_halfletter_cut_stack',
    title: 'Libro Media Carta (Corte y Apilado)',
    category: 'Libro',
    description: 'Modo Cut & Stack en pliego Tabloide: se corta al medio y la pila izquierda va sobre la derecha.',
    icon: '📚',
    badge: 'Cut & Stack',
    settings: {
      sheetPreset: 'Tabloid',
      sheetWidth: 279.4,
      sheetHeight: 431.8,
      sheetOrientation: 'landscape',
      layoutMode: 'cut_and_stack',
      gridCols: 2,
      gridRows: 1,
      targetPagePreset: 'HalfLetter',
      targetPageWidth: 139.7,
      targetPageHeight: 215.9,
      duplexMode: 'long_edge',
      bindingEdge: 'left',
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 10,
      marginRight: 10,
      gutterHorizontal: 0,
      gutterVertical: 0,
      drawCropMarks: true,
      cropMarkLength: 5,
      bleed: 3,
      scaleMode: 'fit',
    },
  },
  {
    id: 'stickers_9up_a4',
    title: '9 Stickers / Etiquetas Cuadradas en A4',
    category: 'Papelería',
    description: 'Grilla 3×3 simétrica en pliego A4 con calles de 5 mm para corte con regla o plotter.',
    icon: '🏷️',
    badge: '3×3 A4',
    settings: {
      sheetPreset: 'A4',
      sheetWidth: 210,
      sheetHeight: 297,
      sheetOrientation: 'portrait',
      layoutMode: 'step_and_repeat',
      gridCols: 3,
      gridRows: 3,
      targetPagePreset: 'Custom',
      targetPageWidth: 60,
      targetPageHeight: 60,
      duplexMode: 'simplex',
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 10,
      marginRight: 10,
      gutterHorizontal: 5,
      gutterVertical: 5,
      drawCropMarks: true,
      cropMarkLength: 4,
      bleed: 2,
      scaleMode: 'fit',
    },
  },
];
