import { ImpositionSettings } from '../types';

export const DEFAULT_SETTINGS: ImpositionSettings = {
  sheetPreset: 'A4',
  sheetWidth: 210,
  sheetHeight: 297,
  sheetOrientation: 'landscape',
  targetPagePreset: 'auto',
  targetPageWidth: 148.5,
  targetPageHeight: 210,
  gridCols: 2,
  gridRows: 1,
  layoutMode: 'booklet',
  duplexMode: 'long_edge',
  gridOrder: 'rows',
  bindingEdge: 'left',
  signatureSize: 0,
  duplexItemMode: 'two_page_items',
  booklet4UpMode: 'cut_and_nest',
  splitDoubleSpreads: false,
  excludedPageIndices: [],
  pageRotation: 0,
  reverseRotation: 0,
  autoRotateToFit: true,
  scaleMode: 'fit',
  customScale: 100,
  marginTop: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  gutterHorizontal: 0,
  gutterVertical: 0,
  drawCropMarks: true,
  cropMarkLength: 5,
  bleed: 2,
};
